version: '3.9'

services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile.build
    volumes:
      - ./backend:/app/backend
    ports:
      - "8000:8000"
    stdin_open: true
    tty: true
    depends_on:
      - db
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings.build

  db:
    container_name: db
    image: postgres:11.1-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres-data: