version: '3.9'

services:
  backend:
    build:
      context: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    volumes:
      - ./backend:/backend
    depends_on:
      - db
  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/frontend
    ports:
      - 3000:3000
    image: app:react
    container_name: react_container
    command: npm start
    depends_on:
      - backend
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=chess_manager
      - POSTGRES_USER=chess_admin
      - POSTGRES_PASSWORD=chess8802?