version: '3.9'

services:
  backend:
    build:
      context: ./backend
    command: gunicorn core.wsgi --bind 0.0.0.0:8000 --reload
    ports:
      - 8000:8000
    volumes:
      - ./backend:/backend
    container_name:
      backend
    depends_on:
      - db
  frontend:
    image: app:react
    build:
      context: ./frontend
    environment:
      CHOKIDAR_USEPOLLING: "true"
    command: npm start
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
    container_name: frontend
    depends_on:
      - backend
  db:
    image: postgres:11.1-alpine
    volumes:
      - ./data/db:/var/lib/postgresql/data
    container_name: db