# Generated by Django 3.2.8 on 2021-11-01 15:54

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0001_initial'),
        ('user_profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tournament_id', models.IntegerField(blank=True, editable=False, null=True)),
                ('tournament_name', models.CharField(max_length=70)),
                ('total_rounds', models.IntegerField(default=4, editable=False)),
                ('finished_rounds', models.IntegerField(default=0, editable=False)),
                ('players_list', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), size=8)),
                ('ready_to_start', models.BooleanField(blank=True, default=False, null=True)),
                ('started', models.BooleanField(blank=True, default=False, editable=False, null=True)),
                ('completed', models.BooleanField(blank=True, default=False, editable=False, null=True)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_profiles.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='players.player')),
                ('tournament', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='tournaments.tournament')),
            ],
        ),
    ]
