# Generated by Django 3.2.8 on 2021-10-31 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_profiles', '0002_alter_profile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tournament_id', models.IntegerField(blank=True, editable=False, null=True)),
                ('tournament_name', models.CharField(default='tournament', max_length=70)),
                ('total_rounds', models.IntegerField(default=4, editable=False)),
                ('status', models.CharField(choices=[('1', 'awaiting_players'), ('2', 'can_be_started'), ('3', 'tournament_over')], default='1', max_length=1)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_profiles.profile')),
            ],
        ),
    ]
