# Generated by Django 3.2.8 on 2021-10-31 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0002_auto_20211031_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='status',
            field=models.CharField(choices=[('1', 'awaiting_players'), ('2', 'can_be_started'), ('3', 'tournament_over')], default='1', editable=False, max_length=1),
        ),
    ]
