# Generated by Django 3.2.8 on 2021-10-31 19:35

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0003_alter_tournament_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='players_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=[], size=8),
            preserve_default=False,
        ),
    ]
