# Generated by Django 3.2.8 on 2021-10-31 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0004_tournament_players_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='finished_rounds',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
