# Generated by Django 3.2.8 on 2021-11-01 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_id', models.IntegerField(blank=True, editable=False, null=True)),
                ('username', models.CharField(max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('rank', models.IntegerField(blank=True, editable=False, null=True)),
                ('tournaments_played', models.IntegerField(blank=True, default=0, editable=False, null=True)),
                ('tournaments_won', models.IntegerField(blank=True, default=0, editable=False, null=True)),
                ('matches_played', models.IntegerField(blank=True, default=0, editable=False, null=True)),
                ('matches_won', models.IntegerField(blank=True, default=0, editable=False, null=True)),
                ('avg_place', models.FloatField(blank=True, default=0, editable=False, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_profiles.profile')),
            ],
            options={
                'verbose_name': 'Joueur',
            },
        ),
    ]
