# Generated by Django 3.2.8 on 2021-10-28 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0002_alter_profile_user'),
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_profiles.profile'),
        ),
        migrations.AlterField(
            model_name='player',
            name='rank',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
