# Generated by Django 3.2.8 on 2021-11-01 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='player_id',
            new_name='number',
        ),
    ]
