# Generated by Django 3.2.8 on 2021-10-29 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_auto_20211028_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='matches_played',
            field=models.IntegerField(blank=True, default=0, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='tournaments_played',
            field=models.IntegerField(blank=True, default=0, editable=False, null=True),
        ),
    ]
