# Generated by Django 3.2.8 on 2021-10-31 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0002_alter_profile_user'),
        ('players', '0003_auto_20211029_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_profiles.profile'),
        ),
    ]
